services:
  - type: web
    name: discord-bot
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DASHBOARD_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
